// <auto-generated />
using System;
using DAWW.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAWW.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DAWW.Models.Achizitie", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<int>("IdProdus")
                        .HasColumnType("int");

                    b.Property<int>("IdComanda")
                        .HasColumnType("int");

                    b.HasKey("IdUser", "IdProdus", "IdComanda");

                    b.HasIndex("IdComanda");

                    b.HasIndex("IdProdus");

                    b.ToTable("Achizitii");
                });

            modelBuilder.Entity("DAWW.Models.Adresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Apartament")
                        .HasColumnType("int");

                    b.Property<string>("Bloc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CodPostal")
                        .HasColumnType("int");

                    b.Property<string>("Numar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oras")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Scara")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Strada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tara")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Adrese");
                });

            modelBuilder.Entity("DAWW.Models.Comanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataPlasare")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdLivrare")
                        .HasColumnType("int");

                    b.Property<int>("IdPlata")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdLivrare")
                        .IsUnique();

                    b.HasIndex("IdPlata")
                        .IsUnique();

                    b.ToTable("Comenzi");
                });

            modelBuilder.Entity("DAWW.Models.Livrare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("Easybox")
                        .HasColumnType("int");

                    b.Property<string>("FirmaCurierat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdAdresa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAdresa");

                    b.ToTable("Livrari");
                });

            modelBuilder.Entity("DAWW.Models.Plata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metoda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Suma")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Plati");
                });

            modelBuilder.Entity("DAWW.Models.Produs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descriere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Pret")
                        .HasColumnType("real");

                    b.Property<string>("Producator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Reducere")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Produse");
                });

            modelBuilder.Entity("DAWW.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Useri");
                });

            modelBuilder.Entity("DAWW.Models.Achizitie", b =>
                {
                    b.HasOne("DAWW.Models.Comanda", "Comanda")
                        .WithMany("Achizitii")
                        .HasForeignKey("IdComanda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAWW.Models.Produs", "Produs")
                        .WithMany("Achizitii")
                        .HasForeignKey("IdProdus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAWW.Models.User", "User")
                        .WithMany("Achizitii")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comanda");

                    b.Navigation("Produs");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAWW.Models.Comanda", b =>
                {
                    b.HasOne("DAWW.Models.Livrare", "Livrare")
                        .WithOne("Comanda")
                        .HasForeignKey("DAWW.Models.Comanda", "IdLivrare")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAWW.Models.Plata", "Plata")
                        .WithOne("Comanda")
                        .HasForeignKey("DAWW.Models.Comanda", "IdPlata")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livrare");

                    b.Navigation("Plata");
                });

            modelBuilder.Entity("DAWW.Models.Livrare", b =>
                {
                    b.HasOne("DAWW.Models.Adresa", "Adresa")
                        .WithMany("Livrari")
                        .HasForeignKey("IdAdresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adresa");
                });

            modelBuilder.Entity("DAWW.Models.Adresa", b =>
                {
                    b.Navigation("Livrari");
                });

            modelBuilder.Entity("DAWW.Models.Comanda", b =>
                {
                    b.Navigation("Achizitii");
                });

            modelBuilder.Entity("DAWW.Models.Livrare", b =>
                {
                    b.Navigation("Comanda")
                        .IsRequired();
                });

            modelBuilder.Entity("DAWW.Models.Plata", b =>
                {
                    b.Navigation("Comanda")
                        .IsRequired();
                });

            modelBuilder.Entity("DAWW.Models.Produs", b =>
                {
                    b.Navigation("Achizitii");
                });

            modelBuilder.Entity("DAWW.Models.User", b =>
                {
                    b.Navigation("Achizitii");
                });
#pragma warning restore 612, 618
        }
    }
}
